name: qurani
description: A Flutter app that wraps the Qurani.info website in a WebView.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  package_info_plus: ^9.0.0
  sqflite: ^2.3.3
  path: ^1.9.0
  just_audio: ^0.9.39
  just_audio_background: ^0.0.1-beta.17
  audio_session: ^0.1.16
  permission_handler: ^11.0.1
  flutter_qiblah: ^3.1.0+1
  dio: ^5.4.0
  intl: ^0.20.2
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  share_plus: ^7.2.1
  in_app_update: ^4.2.2
  webview_flutter: ^4.7.0
  adhan_dart: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  sqlite3: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/data/
    - assets/data/quran.db
    - assets/data/quran-simple/pages/
    - assets/data/quran-simple/quran.json
    - assets/data/quran-uthmani/pages/
    - assets/data/quran-uthmani/quran.json
    - assets/data/quran-english/pages/
    - assets/data/quran-english/quran.json
    - assets/data/quran-french/pages/
    - assets/data/quran-french/quran.json
    - assets/data/quran_muyassar/pages/
    - assets/data/quran_muyassar/quran.json
    - public/
  fonts:
      - family: Amiri Quran
        fonts:
          - asset: assets/fonts/AmiriQuran-Regular.ttf