name: qurani
description: >
  Qurani is a comprehensive Islamic companion app featuring the complete Holy Quran with multiple translations,
  accurate prayer times with customizable Adhan notifications, Qibla direction finder, Tasbeeh counter,
  memorization tools, and audio recitations. Designed for Muslims worldwide with support for Arabic, English,
  and French languages. All Quran text and core features work offline.

publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # --- Core Utilities ---
  package_info_plus: ^9.0.0
  device_info_plus: ^12.2.0
  path_provider: ^2.1.3
  shared_preferences: ^2.3.2
  permission_handler: ^11.3.1  
  
  # --- Audio & Background ---
  just_audio: ^0.9.42          
  just_audio_background: ^0.0.1-beta.17 
  audio_session: ^0.1.21       

  # --- Database & Storage ---
  sqflite: ^2.3.3
  path: ^1.9.0

  # --- UI & Icons ---
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.7
  in_app_update: ^4.2.2
  webview_flutter: ^4.7.0
  pdfrx: ^2.2.18 

  # --- Notifications & Alarms ---
  flutter_local_notifications: ^18.0.1 
  android_alarm_manager_plus: ^5.0.0
  timezone: ^0.9.2
  flutter_timezone: ^5.0.1

  # --- Network & Tools ---
  dio: ^5.4.0
  url_launcher: ^6.3.1
  share_plus: ^7.2.1
  uuid: ^4.5.2
  # [FIXED] Updated to match your Flutter SDK requirement
  intl: ^0.20.2                
  pdf: ^3.10.7
  geocoding: ^2.1.1
  flutter_qiblah: ^3.1.0+1

  geolocator: any
  http: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^3.0.0        
  sqlite3: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/data/
    - assets/data/quran.db
    - assets/data/reciters.json
    - assets/audio/
    - public/
  fonts:
      - family: Amiri Quran
        fonts:
          - asset: assets/fonts/AmiriQuran-Regular.ttf
      - family: KFGQPCHafsSmall
        fonts:
          - asset: assets/fonts/KfgqpcHafsUthmanicScriptRegular-nARZ1.ttf
      - family: KFGQPCHafsLarge
        fonts:
          - asset: assets/fonts/KfgqpcHafsUthmanicScriptRegular-1jGEe.ttf
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
